replicaCount: 2

deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

configMap:
  data:
    PORT: "4003"
    MEDIA_EVENTS_ENABLED: "true"
    S3_ENDPOINT: http://platform-prd-minio.platform-prd.svc.cluster.local:9000
    S3_PRESIGN_ENDPOINT: https://uploads.mereb.app
    S3_REGION: us-east-1
    S3_BUCKET: media
    MEDIA_CDN_ORIGIN: https://uploads.mereb.app/media
    SPLUNK_HEC_URL: https://splunk-hec.mereb.app/services/collector/event
    SPLUNK_HEC_INDEX: logs-prd

resources:
  requests:
    cpu: 75m
    memory: 224Mi
  limits:
    cpu: 450m
    memory: 640Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
