replicaCount: 1

configMap:
  data:
    PORT: "4003"
    MEDIA_EVENTS_ENABLED: "true"
    S3_ENDPOINT: http://platform-stg-minio.platform-stg.svc.cluster.local:9000
    S3_PRESIGN_ENDPOINT: https://uploads-stg.mereb.app
    S3_REGION: us-east-1
    S3_BUCKET: media-stg
    MEDIA_CDN_ORIGIN: https://uploads-stg.mereb.app/media-stg
    SPLUNK_HEC_URL: https://splunk-hec.mereb.app/services/collector/event
    SPLUNK_HEC_INDEX: logs-stg

resources:
  requests:
    cpu: 15m
    memory: 96Mi
  limits:
    cpu: 150m
    memory: 256Mi
